language: python

python:
  - "3.5.2"

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

script:
  - py.test --cov=app && coverage report

after_success:
    - coveralls
